owner: tapitechsolutions # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: thera-monit

sites: # List of endpoints to track
  - name: Thera-Main
    url: https://onboarding.therapiasoftware.com/sign_up
  - name: Thera-Client
    url: https://ops.therapiaclient.com/client/sign_in
  - name: Thera-Admin
    url: https://therasoftware.net/admins/sign_in
  - name: Thera-Billing
    url: https://ops.therapiabilling.com/users/sign_in
  - name: Thera-Support
    url: https://ops.therapiasupport.com/en
  - name: Thera-Family
    url: https://ops.therapiafamily.com/family/sign_in
  - name: Thera-Connect
    url: https://ops.therapiaconnecta.com/referrals/sign_in
  - name: Thera-Telehealth
    url: https://telehealth.therapiasoftware.com/test
assignees: # Users to assign downtime issues (optional)
  - tapitechsolutions

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
notify:
  - name: email
    webhook: https://api.sendgrid.com/v3/mail/send
    method: POST
    headers:
      Authorization: Bearer ${{secrets.sendgrid.SENDGRID_API_KEY}}
      Content-Type: application/json
    body:
      personalizations:
        - to:
            - email: arvind@tapitechinc.com
          subject: "Upptime notification: {{checkName}} is {{checkStatus}}"
      from:
        email: donotreply@therapiasoftware.com
      content:
        - type: text/plain
          value: "{{checkName}} is {{checkStatus}} at {{checkUrl}}."
